<?php
/**
 * Страница "Форма добавления / редактирования изображения фотоальбома".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью расширения модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Form for adding / editing image album</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/gallery-form.png' ?>" />
    </div>
    <p>The form appears after clicking the <b>"Add"</b> button on the albums list toolbar or selecting the <b>"Edit"</b> item from the context menu of the selected entry.</p>
    <h2>Form tabs</h2>
    <h3>Form tab "Common"</h3>
    <p>The form tab displays the basic attributes of the photo album and has the following fields:</p>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Name.</b> Name of the photo album of the media gallery;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Description.</b> Description of the photo album of the media gallery;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Author.</b> Author of the photo album of the media gallery;</li>
        <li><span class="g-help-fld g-help-fld_checkbox"></span> <b>Published.</b> Publish or unpublish (hide) a media gallery photo album.</li>
    </ul>

    <h3>Form tab "Settings"</h3>
    <p>The form tab displays the photo album settings and has the following fields</p>
    <p>Fieldset "Thumbnail size"</p>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_spinner"></span> <b>Maximum width, px.</b> Maximum thumbnail width in pixels (default 150 px);</li>
        <li><span class="g-help-fld g-help-fld_spinner"></span> <b>Maximum height, px.</b> Maximum thumbnail height in pixels (default 150 px);</li>
        <li><span class="g-help-fld g-help-fld_checkbox"></span> <b>Crop image to size.</b> Crops the thumbnail to the specified size if the flag is set;</li>
        <li><span class="g-help-fld g-help-fld_checkbox"></span> <b>Add watermark.</b> Adds a thumbnail watermark if the flag is set.</li>
    </ul>
    <p>Fieldset "Original size"</p>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_spinner"></span> <b>Maximum width, px.</b> The maximum width of the original image in pixels (default is 1024 px);</li>
        <li><span class="g-help-fld g-help-fld_spinner"></span> <b>Maximum height, px.</b> Maximum height of the original image in pixels (default 150 px);</li>
        <li><span class="g-help-fld g-help-fld_checkbox"></span> <b>Crop image to size.</b> Crops the original image to the specified size if the flag is set;</li>
        <li><span class="g-help-fld g-help-fld_checkbox"></span> <b>Add watermark.</b> Adds a watermark of the original image if the flag is set.</li>
    </ul>

    <h3>Form tab "Uploading"</h3>
    <p>You can go to the "Upload" form tab only after filling in the previous "General" and "Settings" tabs. The tab allows you to perform both single and multiple file uploads.</p>
</article>