<?php
/**
 * Страница "Содержание".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью виджета веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Plugin "Image album"</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>The plugin is designed to manage images of image albums of the media gallery.</p>

    <h2>Contents:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('gallery-form') ?>">Form for adding / editing image album</a></li>
        <li><a href="<?= $url('item-form') ?>">Form for adding / editing album image</a></li>
        <li><a href="<?= $url('items-grid') ?>">List of album images</a></li>
    </ul>
</article>