<?php
/**
 * Страница "Список изображений фотоальбома".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Список изображений фотоальбома</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/items-grid.png' ?>" />
    </div>
    <p>В списке отображаются изображения выбранного фотоальбома.</p>
    <h2>Столбцы списка</h2>
    <ul class="g-help-list">
        <li><b>ID.</b> Идентификатор изображений фотоальбома;</li>
        <li><b>Порякдовый номер.</b> Порядковый номер изображения в фотоальбоме;</li>
        <li><b>Название.</b> Название изображения;</li>
        <li><b>Описание.</b> Описание изображения;</li>
        <li><b>Изображение / Файл.</b> Имя файла изображения;</li>
        <li><b>Изображение / Формат.</b> Формат (расширение) файла изображения;</li>
        <li><b>Изображение / Размер (Мб).</b> Размер файла изображения в мегабайтах;</li>
        <li><b>Изображение / Размер (пкс).</b> Размер (ширина x высота) изображения в пикселях;</li>
        <li><b>Миниатюра / Файл.</b> Имя файла миниатюры изображения;</li>
        <li><b>Миниатюра / Размер (пкс).</b> Размер (ширина x высота) изображения миниатюры;</li>
        <li><b>Отображается в фотоальбоме.</b> Показывать изображение в фотоальбоме, если флаг установлен.</li>
    </ul>

    <h2>Панель инструментов</h2>
    <ul class="g-help-list">
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-img-add.svg' ?>" /> <b>Добавить изображение.</b> Вызывает форму для добавления изображения в фотоальбом;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-img-delete.svg' ?>" /> <b>Удалить.</b> Удаляет выделенные изображения из фотоальбома;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/cleanup.svg' ?>" /> <b>Очистить.</b> Удаляет все изображения из фотоальбома;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-edit.svg' ?>" /> <b>Правка.</b> Вызвает форму для редактирования изображения фотоальбома;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-select.svg' ?>" /> <b>Выделить.</b> Выделяет или убирает выделение изображений в фотоальбоме;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/refresh.svg' ?>" /> <b>Обновить.</b> Обновляет список изображений фотоальбома;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-profiling-off.svg' ?>" /> <b>Профилирование записи.</b> Разворачивает или сворачивает Панель навигации для отображения информации об изображении фотоальбома;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-toggle-columns-off.svg' ?>" /> <b>Показать.</b> Показывает  скрытые столбцы;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/help.svg' ?>" /> <b>Справка.</b> Вызывает окно справочной информации для текущего списка;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/search.svg' ?>" /> <b>Поиск.</b> Вызывает форму поиска записей в списке.</li>
    </ul>
</article>