<?php
/**
 * Страница "Список изображений фотоальбома".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>List of album images</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/items-grid.png' ?>" />
    </div>
    <p>The list displays images from the selected photo album.</p>
    <h2>List columns</h2>
    <ul class="g-help-list">
        <li><b>ID.</b> Photo album image identifier;</li>
        <li><b>Index.</b> The index number of the image in the photo album;</li>
        <li><b>Name.</b> Image title;</li>
        <li><b>Description.</b> Image description;</li>
        <li><b>Image / File.</b> Image file name;</li>
        <li><b>Image / Format.</b> Image file format (extension);</li>
        <li><b>Image / Size (Mb).</b> Image file size in megabytes;</li>
        <li><b>Image / Size (px).</b> The size (width x height) of the image in pixels;</li>
        <li><b>Thumb / File.</b> Thumbnail image file size;</li>
        <li><b>Thumb / Size (px).</b> The size (width x height) of the thumbnail image;</li>
        <li><b>Visible.</b> Show image in photo album if flag is set.</li>
    </ul>

    <h2>Toolbar</h2>
    <ul class="g-help-list">
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-img-add.svg' ?>" /> <b>Add image.</b> Shows a form for adding an image to a photo album;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-img-delete.svg' ?>" /> <b>Delete.</b> Delete selected images from the photo album;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/cleanup.svg' ?>" /> <b>Clear.</b> Deletes all images from a photo album;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-edit.svg' ?>" /> <b>Edit.</b> Sgows a form for editing a photo album image;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-select.svg' ?>" /> <b>Select.</b> Selects or deselects images in a photo album;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/refresh.svg' ?>" /> <b>Refresh.</b> Refreshes the list of images in the photo album;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-profiling-off.svg' ?>" /> <b>Record profiling.</b> Expands or collapses the Navigation Bar to display information about a photo album image;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-toggle-columns-off.svg' ?>" /> <b>Show.</b> Shows hidden columns;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/help.svg' ?>" /> <b>Help.</b> Shows the help window for the current list;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/search.svg' ?>" /> <b>Search.</b> Shows a form to search for records in a list.</li>
    </ul>
</article>