<?php
/**
 * Страница "Форма добавления / редактирования изображения фотоальбома".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью расширения модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Form for adding / editing album image</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/item-form.png' ?>" />
    </div>
    <p>The form appears after clicking the <b>"Add"</b> button on the elements list toolbar or selecting the <b>"Edit"</b> image item from the context menu of the selected entry.</p>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Name.</b> Image title;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Description.</b> Image description;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Author.</b> Image author;</li>
        <li><b>Image.</b> Information about the uploaded file (file name, format, file size, image size);</li>
        <li><b>Thumb.</b> Thumbnail image information (file name, format, file size, thumbnail size);</li>
        <li><span class="g-help-fld g-help-fld_checkbox"></span> <b>Visible.</b> Shows the image in the photo album if the flag is set.</li>
    </ul>
</article>